language:
  - minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test-ecosystem
  - docker images

script: docker run -e TRAVIS_COMMIT_RANGE="HEAD^1...HEAD" -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test-ecosystem
